### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by MichielvdVelde** [MichielvdVelde/redis-streams-manager#5]
Current versions do not follow semver because they are considered unstable. Even minor version updates may contain breaking changes.

The module is considered stable when I have used it effectively in the personal project it was extracted from. When the use cases are covered by the module's features (i.e. I don't have to update it because of the requirements of my project)., I will consider the module stable and release version 1.

From then on the module updates will follow semver.

Issues to be solved (incomplete list):

- [x] Ability to customize blocking timeout (#7)
- [x] Ability to set entry count (#8)
- [x] Add streams size (#9)

**Comment by MichielvdVelde** [comment]
Stable version 1.0.0 has now been released.
